import { StyleSheet } from "react-native";
import { colors, shadows, radii } from "../constants/tokens";

export const communityStyles = StyleSheet.create({
  // ── Shell ────────────────────────────────────────────────
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },

  // ── Fixed page header ────────────────────────────────────
  header: {
    backgroundColor: colors.surface,
    paddingHorizontal: 20,
    paddingTop: 6,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerLeft: {
    flex: 1,
  },
  title: {
    fontSize: 22,
    fontWeight: "800",
    color: colors.textPrimary,
    letterSpacing: -0.3,
  },
  subtitle: {
    fontSize: 13,
    color: colors.textSecondary,
    marginTop: 2,
    fontWeight: "500",
  },

  // ── Segmented tab bar ────────────────────────────────────
  tabContainer: {
    flexDirection: "row",
    backgroundColor: "#E5E7EB",
    borderRadius: radii.md,
    marginHorizontal: 16,
    marginTop: 14,
    marginBottom: 14,
    padding: 3,
  },
  tab: {
    flex: 1,
    paddingVertical: 9,
    alignItems: "center",
    borderRadius: 10,
  },
  activeTab: {
    backgroundColor: colors.surface,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  tabText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#9CA3AF",
  },
  activeTabText: {
    color: colors.accent,
  },

  // ── Search bar ───────────────────────────────────────────
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.md,
    marginHorizontal: 16,
    marginBottom: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: colors.textPrimary,
    fontWeight: "500",
  },

  // ── Count strip ──────────────────────────────────────────
  countStrip: {
    paddingHorizontal: 20,
    paddingBottom: 10,
  },
  countStripText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.textTertiary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },

  // ── List content ─────────────────────────────────────────
  listContent: {
    paddingHorizontal: 16,
    paddingBottom: 110,
  },

  // ── Announcement card ────────────────────────────────────
  announcementCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: 16,
    marginBottom: 10,
    ...shadows.sm,
    overflow: "hidden",
  },
  announcementUnread: {
    // Left border removed; unread dot handled in JSX
  },
  announcementUnreadDot: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: colors.accent,
  },
  announcementBadgesRow: {
    flexDirection: "row",
    gap: 6,
    flexWrap: "wrap",
    marginBottom: 8,
  },
  announcementTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.textPrimary,
    marginBottom: 5,
    lineHeight: 21,
  },
  announcementBody: {
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 20,
  },
  announcementMeta: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
    gap: 6,
  },
  announcementDate: {
    fontSize: 12,
    color: colors.textTertiary,
    fontWeight: "500",
  },
  announcementDateRight: {
    marginLeft: "auto",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },

  // ── Forum post card ──────────────────────────────────────
  forumCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: 16,
    marginBottom: 10,
    ...shadows.sm,
  },
  forumCardTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  forumAvatar: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  forumAvatarText: {
    fontSize: 13,
    fontWeight: "700",
  },
  forumAuthorName: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  forumAuthorTime: {
    fontSize: 11,
    color: colors.textTertiary,
    marginTop: 1,
  },
  forumTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.textPrimary,
    marginBottom: 12,
    lineHeight: 21,
  },
  forumBody: {
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 19,
    marginBottom: 12,
  },
  forumFooter: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
  },
  forumStat: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  forumStatText: {
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: "600",
  },

  // ── Poll card ────────────────────────────────────────────
  pollCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: 16,
    marginBottom: 10,
    ...shadows.sm,
  },
  pollTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.textPrimary,
    marginBottom: 4,
    lineHeight: 21,
  },
  pollMeta: {
    fontSize: 12,
    color: colors.textTertiary,
    marginBottom: 14,
    fontWeight: "500",
  },
  pollClosedBadge: {
    alignSelf: "flex-start",
    backgroundColor: colors.dangerLight,
    borderRadius: radii.sm,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: 12,
  },
  pollClosedBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.danger,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  pollOption: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    gap: 10,
    backgroundColor: colors.background,
    borderRadius: 10,
    padding: 12,
    borderWidth: 1.5,
    borderColor: colors.border,
  },
  pollOptionSelected: {
    borderColor: colors.accent,
    backgroundColor: colors.accentLight,
  },
  pollOptionText: {
    fontSize: 14,
    color: colors.textSecondary,
    flex: 1,
    fontWeight: "500",
  },
  pollOptionTextSelected: {
    color: colors.textPrimary,
    fontWeight: "700",
  },
  pollCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#D1D5DB",
    justifyContent: "center",
    alignItems: "center",
  },
  pollCircleSelected: {
    borderColor: colors.accent,
    backgroundColor: colors.accent,
  },
  pollCheckbox: {
    width: 20,
    height: 20,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: "#D1D5DB",
    justifyContent: "center",
    alignItems: "center",
  },
  pollCheckboxSelected: {
    borderColor: colors.accent,
    backgroundColor: colors.accent,
  },
  pollSubmitBtn: {
    backgroundColor: colors.accent,
    borderRadius: radii.md,
    paddingVertical: 13,
    alignItems: "center",
    marginTop: 6,
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  pollSubmitText: {
    color: colors.surface,
    fontWeight: "700",
    fontSize: 14,
    letterSpacing: 0.2,
  },
  pollSubmitDisabled: {
    backgroundColor: "#9CA3AF",
    shadowOpacity: 0,
    elevation: 0,
  },

  // ── Poll results bar chart ───────────────────────────────
  barRow: {
    marginBottom: 12,
  },
  barLabel: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 5,
    alignItems: "center",
  },
  barLabelText: {
    fontSize: 13,
    color: colors.textSecondary,
    flex: 1,
    fontWeight: "500",
    marginRight: 8,
  },
  barLabelPct: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  barBg: {
    height: 8,
    backgroundColor: colors.border,
    borderRadius: 4,
    overflow: "hidden",
  },
  barFill: {
    height: "100%",
    backgroundColor: colors.textTertiary,
    borderRadius: 4,
  },
  barFillWinner: {
    backgroundColor: colors.accent,
  },
  pollClosed: {
    fontSize: 12,
    color: colors.danger,
    fontWeight: "600",
    marginTop: 10,
    textAlign: "center",
  },

  // ── FAB ──────────────────────────────────────────────────
  fab: {
    position: "absolute",
    right: 20,
    bottom: 28,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.accent,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
  },

  // ── Detail screen ────────────────────────────────────────
  detailContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  detailScroll: {
    padding: 16,
    paddingBottom: 40,
  },
  detailTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: colors.textPrimary,
    marginBottom: 12,
    lineHeight: 28,
  },
  detailBody: {
    fontSize: 15,
    color: colors.textSecondary,
    lineHeight: 24,
    marginTop: 14,
  },
  detailSection: {
    marginTop: 16,
  },

  // ── Thread / create-post ─────────────────────────────────
  replyBar: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.surface,
    gap: 10,
  },
  replyInput: {
    flex: 1,
    backgroundColor: colors.background,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 14,
    color: colors.textPrimary,
    maxHeight: 80,
  },
  replySendBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.accent,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  replyCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    padding: 12,
    marginBottom: 8,
    ...shadows.sm,
  },
  replyText: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
    marginTop: 6,
  },
  createField: {
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    padding: 14,
    marginBottom: 12,
    fontSize: 15,
    color: colors.textPrimary,
    borderWidth: 1,
    borderColor: colors.border,
  },
  createFieldMulti: {
    minHeight: 120,
    textAlignVertical: "top",
  },
  imagePickerRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 16,
  },
  imagePickerAdd: {
    width: 72,
    height: 72,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: colors.accent,
    borderStyle: "dashed",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.background,
  },
  imagePickerThumb: {
    width: 72,
    height: 72,
    borderRadius: 10,
    overflow: "hidden",
  },
  imagePickerThumbImg: {
    width: "100%",
    height: "100%",
  },
  imageRemove: {
    position: "absolute",
    top: 2,
    right: 2,
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  submitBtn: {
    backgroundColor: colors.accent,
    borderRadius: 14,
    paddingVertical: 15,
    alignItems: "center",
    marginTop: 4,
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 4,
  },
  submitBtnText: {
    color: colors.surface,
    fontWeight: "700",
    fontSize: 15,
    letterSpacing: 0.2,
  },
  submitBtnDisabled: {
    backgroundColor: "#9CA3AF",
    shadowOpacity: 0,
    elevation: 0,
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: 16,
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 10,
  },
});
