import { StyleSheet } from "react-native";
import { colors, shadows, radii } from "../constants/tokens";

export const dashboardStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 120,
    gap: 22,
  },

  /* ===== NEW HOME LAYOUT ===== */
  scrollContent: {
    paddingBottom: 120,
  },

  /* GRADIENT HEADER */
  headerGradient: {
    paddingHorizontal: 20,
    paddingBottom: 26,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  headerTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  headerIconBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerLocation: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    flex: 1,
    justifyContent: "center",
  },
  headerLocationText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 14,
    maxWidth: 160,
  },
  headerAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    overflow: "hidden",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.5)",
  },
  headerAvatarInitials: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.25)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerAvatarInitialsText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 13,
  },
  headerGreeting: {
    color: "#FFFFFF",
    fontSize: 26,
    fontWeight: "800",
    letterSpacing: -0.5,
  },
  headerSubtitle: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 14,
    marginTop: 4,
    marginBottom: 18,
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#FFFFFF",
    borderRadius: radii.full,
    paddingHorizontal: 16,
    paddingVertical: 14,
    ...shadows.md,
  },
  searchPlaceholder: {
    color: colors.textTertiary,
    fontSize: 14,
    fontWeight: "500",
  },

  /* BODY */
  body: {
    paddingHorizontal: 20,
    paddingTop: 22,
    gap: 20,
  },

  /* SERVICES LIST */
  serviceList: {
    backgroundColor: colors.surface,
    borderRadius: radii.xl,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: colors.border,
    marginTop: 12,
    ...shadows.sm,
  },
  serviceRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    gap: 14,
  },
  serviceRowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
  },
  serviceIcon: {
    width: 46,
    height: 46,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  serviceTextWrap: {
    flex: 1,
  },
  serviceTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  serviceDesc: {
    fontSize: 12.5,
    color: colors.textSecondary,
    marginTop: 2,
  },

  /* SUBSCRIPTION PROMO BANNER */
  promoBanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.textPrimary,
    borderRadius: radii.xl,
    padding: 20,
    ...shadows.md,
  },
  promoTextWrap: {
    flex: 1,
  },
  promoLabel: {
    color: colors.accentMid,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
    marginBottom: 6,
  },
  promoTitle: {
    color: "#FFFFFF",
    fontSize: 19,
    fontWeight: "800",
    letterSpacing: -0.3,
  },
  promoSubtitle: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 13,
    marginTop: 2,
  },
  promoButton: {
    backgroundColor: colors.accent,
    paddingVertical: 9,
    paddingHorizontal: 18,
    borderRadius: radii.full,
    alignSelf: "flex-start",
    marginTop: 14,
  },
  promoButtonText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 13,
  },
  promoIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 12,
  },

  /* GREETING HEADER ROW */
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  profileAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#E5E7EB",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    borderWidth: 2,
    borderColor: colors.accentMid,
    ...shadows.sm,
  },
  initialsContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.surfaceAlt,
  },
  initialsText: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.textSecondary,
    letterSpacing: 0.5,
  },
  avatarImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },

  /* HEADER (legacy, unused) */
  header: {
    paddingTop: 50,
    paddingHorizontal: 20,
    paddingBottom: 14,
    backgroundColor: colors.surface,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: colors.textPrimary,
  },
  profileButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: colors.accentLight,
    justifyContent: "center",
    alignItems: "center",
  },

  /* GREETING */
  greeting: {
    fontSize: 26,
    fontWeight: "800",
    color: colors.textPrimary,
    letterSpacing: -0.6,
  },
  subGreeting: {
    fontSize: 13,
    color: colors.textSecondary,
    marginTop: 3,
  },

  /* SECTION LABEL (above groups of content) */
  sectionLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.textTertiary,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: -8,
  },

  /* QUICK ACTIONS */
  quickActionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  quickAction: {
    width: "47%",
    flexGrow: 1,
    backgroundColor: colors.surface,
    borderRadius: radii.xl,
    paddingVertical: 18,
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.sm,
  },
  quickActionIcon: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: colors.accentLight,
    justifyContent: "center",
    alignItems: "center",
  },
  quickActionLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.textPrimary,
    textAlign: "center",
  },

  /* HERO */
  heroCard: {
    backgroundColor: colors.accent,
    borderRadius: radii.xl,
    padding: 22,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 16,
    elevation: 6,
  },
  heroText: { flex: 1 },
  heroLabel: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 12,
    textTransform: "uppercase",
    marginBottom: 8,
    fontWeight: "700",
    letterSpacing: 1,
  },
  heroName: {
    fontSize: 22,
    fontWeight: "800",
    color: "#FFFFFF",
    lineHeight: 28,
    letterSpacing: -0.3,
  },
  heroRole: {
    color: "rgba(255,255,255,0.9)",
    marginTop: 4,
    fontSize: 15,
    fontWeight: "500",
  },
  heroDate: {
    color: "rgba(255,255,255,0.65)",
    marginVertical: 12,
    fontSize: 13,
  },
  heroButton: {
    backgroundColor: "#FFFFFF",
    paddingVertical: 12,
    paddingHorizontal: 22,
    borderRadius: radii.full,
    alignSelf: "flex-start",
    marginTop: 4,
  },
  heroButtonText: {
    fontWeight: "800",
    color: colors.accent,
    fontSize: 14,
  },
  heroImage: {
    width: 86,
    height: 86,
    borderRadius: 43,
    marginLeft: 16,
    borderWidth: 3,
    borderColor: "rgba(255, 255, 255, 0.3)",
  },
  heroInitials: {
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  heroInitialsText: {
    fontSize: 28,
    fontWeight: "800",
    color: "#FFFFFF",
    letterSpacing: 1,
  },

  /* ALERT CARD */
  alertCard: {
    backgroundColor: "#FFF7ED",
    borderRadius: radii.xl,
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#FFEDD5",
  },
  alertIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#FFEDD5",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
  },
  alertContent: {
    flex: 1,
  },
  alertTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#9A3412",
    marginBottom: 4,
  },
  alertText: {
    fontSize: 14,
    color: "#C2410C",
    lineHeight: 20,
    fontWeight: "500",
  },
  alertButton: {
    marginTop: 12,
    backgroundColor: "#9A3412",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 10,
    alignSelf: "flex-start",
  },
  alertButtonText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
  },

  /* SUBSCRIPTION CARD - COMPACT */
  subscriptionCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.xl,
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: colors.border,
    borderLeftWidth: 3,
    borderLeftColor: colors.accent,
    ...shadows.sm,
    marginBottom: 10,
  },
  subscriptionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  subscriptionIconContainer: {
    width: 34,
    height: 34,
    borderRadius: radii.sm,
    backgroundColor: colors.accentLight,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  currentPlanLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.textTertiary,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  /* Compact subscription row replaces old subscriptionInfo */
  subscriptionCompactRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  planNameCompact: {
    fontSize: 17,
    fontWeight: "700",
    color: colors.textPrimary,
    flex: 1,
  },
  daysLeftPill: {
    backgroundColor: colors.accentLight,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: radii.full,
  },
  daysLeftPillText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.accent,
  },
  subscriptionFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
  },
  tapToManageText: {
    fontSize: 13,
    color: colors.textSecondary,
    fontWeight: "600",
  },

  /* Legacy subscription styles (used in modal) */
  subscriptionInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  subscriptionLeft: {
    flex: 1,
  },
  planName: {
    fontSize: 28,
    fontWeight: "800",
    color: "#1E293B",
    marginBottom: 4,
  },
  planPrice: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  planPriceMonth: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.textTertiary,
  },
  subscriptionRight: {
    alignItems: "center",
    backgroundColor: colors.warningLight,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: radii.lg,
    borderWidth: 2,
    borderColor: "#FCD34D",
  },
  daysLeftNumber: {
    fontSize: 36,
    fontWeight: "900",
    color: colors.warning,
    lineHeight: 40,
  },
  daysLeftText: {
    fontSize: 13,
    color: "#D97706",
    fontWeight: "700",
    marginTop: 2,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },

  /* SUBSCRIPTION MODAL */
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  subscriptionModalContainer: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    height: "90%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 10,
  },
  subscriptionModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    padding: 24,
    paddingBottom: 16,
    backgroundColor: colors.surface,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  subscriptionModalTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: "#1E293B",
    marginBottom: 4,
  },
  subscriptionModalSubtitle: {
    fontSize: 14,
    color: "#64748B",
    fontWeight: "500",
  },

  /* CURRENT PLAN SECTION */
  currentPlanSection: {
    backgroundColor: colors.surface,
    borderRadius: radii.xl,
    padding: 24,
    marginBottom: 24,
    borderWidth: 2,
    borderColor: colors.success,
    shadowColor: colors.success,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  currentPlanBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.successLight,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    alignSelf: "flex-start",
    marginBottom: 12,
  },
  currentPlanBadgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#059669",
    marginLeft: 6,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  modalCurrentPlanName: {
    fontSize: 32,
    fontWeight: "900",
    color: "#1E293B",
    marginBottom: 8,
  },
  modalCurrentPlanPrice: {
    fontSize: 24,
    fontWeight: "700",
    color: colors.success,
    marginBottom: 16,
  },
  planValidityContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.accentLight,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: radii.md,
  },
  planValidityText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.textPrimary,
    marginLeft: 8,
  },

  /* PLAN SELECTION SECTION */
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1E293B",
    marginBottom: 16,
  },
  planCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: 20,
    borderWidth: 2,
    borderColor: colors.border,
    position: "relative",
    ...shadows.sm,
    marginBottom: 16,
  },
  planCardActive: {
    borderColor: colors.success,
    backgroundColor: "#F0FDF4",
    shadowColor: colors.success,
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  activePlanIndicator: {
    position: "absolute",
    top: 16,
    right: 16,
    zIndex: 1,
  },
  planCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  planCardName: {
    fontSize: 22,
    fontWeight: "800",
    color: "#1E293B",
  },
  planCardNameActive: {
    color: "#059669",
  },
  popularBadge: {
    backgroundColor: colors.warningLight,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: "#FCD34D",
  },
  popularBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#D97706",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  planCardPricing: {
    flexDirection: "row",
    alignItems: "baseline",
    marginBottom: 16,
  },
  planCardPrice: {
    fontSize: 36,
    fontWeight: "900",
    color: "#1E293B",
  },
  planCardPriceActive: {
    color: colors.success,
  },
  planCardPeriod: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.textTertiary,
    marginLeft: 4,
  },
  planCardFeatures: {
    gap: 10,
  },
  featureItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  featureText: {
    fontSize: 14,
    color: colors.textSecondary,
    fontWeight: "500",
    marginLeft: 10,
  },

  /* MODAL UPDATE BUTTON */
  modalUpdateButton: {
    backgroundColor: colors.accent,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 18,
    borderRadius: radii.lg,
    marginBottom: 16,
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  modalUpdateButtonText: {
    color: colors.surface,
    fontSize: 17,
    fontWeight: "700",
    marginRight: 8,
  },

  /* MODAL FOOTER INFO */
  modalFooterInfo: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF7ED",
    padding: 16,
    borderRadius: radii.md,
    marginBottom: 24,
  },
  modalFooterText: {
    fontSize: 13,
    color: "#92400E",
    fontWeight: "500",
    marginLeft: 8,
    flex: 1,
  },

  /* CHAT BUTTON */
  chatButton: {
    position: "absolute",
    bottom: 28,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.accent,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },

  /* CHAT MODAL */
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  chatContainer: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    height: "90%",
    overflow: "hidden",
  },
  chatHeader: {
    backgroundColor: colors.textPrimary,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  chatHeaderTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  chatHeaderSubtitle: {
    fontSize: 13,
    color: "rgba(255, 255, 255, 0.85)",
    marginTop: 2,
    fontWeight: "500",
  },
  messagesList: {
    padding: 20,
    paddingBottom: 20,
  },
  messageBubble: {
    maxWidth: "80%",
    padding: 12,
    borderRadius: radii.lg,
    marginBottom: 4,
  },
  botMessage: {
    backgroundColor: colors.surfaceAlt,
    alignSelf: "flex-start",
    borderBottomLeftRadius: 4,
  },
  userMessage: {
    backgroundColor: colors.accent,
    alignSelf: "flex-end",
    borderBottomRightRadius: 4,
  },
  messageText: {
    fontSize: 15,
    lineHeight: 20,
  },
  botMessageText: {
    color: colors.textPrimary,
  },
  userMessageText: {
    color: "#FFFFFF",
  },

  /* CHAT OPTIONS */
  optionsContainer: {
    marginTop: 8,
    marginBottom: 12,
    gap: 8,
    paddingLeft: 0,
    flexDirection: "column",
    alignItems: "flex-start",
  },
  optionButton: {
    backgroundColor: colors.surface,
    borderWidth: 1.5,
    borderColor: colors.accent,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: radii.lg,
    alignSelf: "flex-start",
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  /* STATS ROW */
  statsRow: {
    flexDirection: "row",
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.sm,
  },
  statIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: colors.surfaceAlt,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  statValue: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.textPrimary,
  },
  statLabel: {
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: "600",
    marginTop: 2,
  },

  optionButtonText: {
    color: colors.accent,
    fontSize: 14,
    fontWeight: "600",
  },
});
