import { StyleSheet } from "react-native";

export const dashboardStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F9FAFB",
  },
  content: {
    padding: 20,
    paddingBottom: 120,
    gap: 24,
  },

  /* HEADER */
  header: {
    paddingTop: 50,
    paddingHorizontal: 20,
    paddingBottom: 14,
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#111827",
  },
  profileButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#EEF2FF",
    justifyContent: "center",
    alignItems: "center",
  },

  /* GREETING */
  greeting: {
    fontSize: 28,
    fontWeight: "800",
    color: "#111827",
  },
  subGreeting: {
    fontSize: 16,
    color: "#6B7280",
  },

  /* HERO */
  heroCard: {
    backgroundColor: "#111827",
    borderRadius: 22,
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
  },
  heroText: { flex: 1 },
  heroLabel: {
    color: "#9CA3AF",
    fontSize: 12,
    textTransform: "uppercase",
    marginBottom: 6,
    fontWeight: "600",
    letterSpacing: 0.5,
  },
  heroName: {
    fontSize: 22,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  heroRole: {
    color: "#D1D5DB",
    marginTop: 4,
    fontSize: 14,
  },
  heroDate: {
    color: "#9CA3AF",
    marginVertical: 10,
    fontSize: 13,
  },
  heroButton: {
    backgroundColor: "#FFFFFF",
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 14,
    alignSelf: "flex-start",
  },
  heroButtonText: {
    fontWeight: "700",
    color: "#111827",
    fontSize: 14,
  },
  heroImage: {
    width: 72,
    height: 72,
    borderRadius: 36,
    marginLeft: 16,
  },

  /* SUBSCRIPTION CARD - ENHANCED */
  subscriptionCard: {
    borderRadius: 20,
    overflow: "hidden",
  },
  subscriptionGradientBorder: {
    backgroundColor: "#6366F1", // Fallback for gradient
    padding: 3,
    borderRadius: 20,
    shadowColor: "#6366F1",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  subscriptionContent: {
    backgroundColor: "#fff",
    borderRadius: 17,
    padding: 20,
  },
  subscriptionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  subscriptionIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#EEF2FF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  currentPlanLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: "#6366F1",
    letterSpacing: 1,
  },
  subscriptionInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  subscriptionLeft: {
    flex: 1,
  },
  planName: {
    fontSize: 28,
    fontWeight: "800",
    color: "#1E293B",
    marginBottom: 4,
  },
  planPrice: {
    fontSize: 20,
    fontWeight: "700",
    color: "#6366F1",
  },
  planPriceMonth: {
    fontSize: 14,
    fontWeight: "600",
    color: "#94A3B8",
  },
  subscriptionRight: {
    alignItems: "center",
    backgroundColor: "#FEF3C7",
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "#FCD34D",
  },
  daysLeftNumber: {
    fontSize: 36,
    fontWeight: "900",
    color: "#F59E0B",
    lineHeight: 40,
  },
  daysLeftText: {
    fontSize: 13,
    color: "#D97706",
    fontWeight: "700",
    marginTop: 2,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  subscriptionFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
  },
  tapToManageText: {
    fontSize: 14,
    color: "#6366F1",
    fontWeight: "600",
  },

  /* SUBSCRIPTION MODAL */
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  subscriptionModalContainer: {
    backgroundColor: "#F8FAFC",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    height: "90%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 10,
  },
  subscriptionModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    padding: 24,
    paddingBottom: 16,
    backgroundColor: "#fff",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
  },
  subscriptionModalTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: "#1E293B",
    marginBottom: 4,
  },
  subscriptionModalSubtitle: {
    fontSize: 14,
    color: "#64748B",
    fontWeight: "500",
  },

  /* CURRENT PLAN SECTION */
  currentPlanSection: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 24,
    marginBottom: 24,
    borderWidth: 2,
    borderColor: "#10B981",
    shadowColor: "#10B981",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  currentPlanBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#D1FAE5",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    alignSelf: "flex-start",
    marginBottom: 12,
  },
  currentPlanBadgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#059669",
    marginLeft: 6,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  modalCurrentPlanName: {
    fontSize: 32,
    fontWeight: "900",
    color: "#1E293B",
    marginBottom: 8,
  },
  modalCurrentPlanPrice: {
    fontSize: 24,
    fontWeight: "700",
    color: "#10B981",
    marginBottom: 16,
  },
  planValidityContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EEF2FF",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
  },
  planValidityText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#4F46E5",
    marginLeft: 8,
  },

  /* PLAN SELECTION SECTION */
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1E293B",
    marginBottom: 16,
  },
  planCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 20,
    borderWidth: 2,
    borderColor: "#E2E8F0",
    position: "relative",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    marginBottom: 16,
  },
  planCardActive: {
    borderColor: "#10B981",
    backgroundColor: "#F0FDF4",
    shadowColor: "#10B981",
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  activePlanIndicator: {
    position: "absolute",
    top: 16,
    right: 16,
    zIndex: 1,
  },
  planCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  planCardName: {
    fontSize: 22,
    fontWeight: "800",
    color: "#1E293B",
  },
  planCardNameActive: {
    color: "#059669",
  },
  popularBadge: {
    backgroundColor: "#FEF3C7",
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#FCD34D",
  },
  popularBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#D97706",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  planCardPricing: {
    flexDirection: "row",
    alignItems: "baseline",
    marginBottom: 16,
  },
  planCardPrice: {
    fontSize: 36,
    fontWeight: "900",
    color: "#1E293B",
  },
  planCardPriceActive: {
    color: "#10B981",
  },
  planCardPeriod: {
    fontSize: 16,
    fontWeight: "600",
    color: "#94A3B8",
    marginLeft: 4,
  },
  planCardFeatures: {
    gap: 10,
  },
  featureItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  featureText: {
    fontSize: 14,
    color: "#475569",
    fontWeight: "500",
    marginLeft: 10,
  },

  /* MODAL UPDATE BUTTON */
  modalUpdateButton: {
    backgroundColor: "#6366F1",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 18,
    borderRadius: 16,
    marginBottom: 16,
    shadowColor: "#6366F1",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  modalUpdateButtonText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "700",
    marginRight: 8,
  },

  /* MODAL FOOTER INFO */
  modalFooterInfo: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF7ED",
    padding: 16,
    borderRadius: 12,
    marginBottom: 24,
  },
  modalFooterText: {
    fontSize: 13,
    color: "#92400E",
    fontWeight: "500",
    marginLeft: 8,
    flex: 1,
  },

  /* CHAT BUTTON */
  chatButton: {
    position: "absolute",
    bottom: 28,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#6366F1",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#6366F1",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },

  /* CHAT MODAL */
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  chatContainer: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    height: "90%",
    overflow: "hidden",
  },
  chatHeader: {
    backgroundColor: "#6366F1",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  chatHeaderTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  chatHeaderSubtitle: {
    fontSize: 13,
    color: "rgba(255, 255, 255, 0.85)",
    marginTop: 2,
    fontWeight: "500",
  },
  messagesList: {
    padding: 20,
    paddingBottom: 20,
  },
  messageBubble: {
    maxWidth: "80%",
    padding: 12,
    borderRadius: 16,
    marginBottom: 4,
  },
  botMessage: {
    backgroundColor: "#F3F4F6",
    alignSelf: "flex-start",
    borderBottomLeftRadius: 4,
  },
  userMessage: {
    backgroundColor: "#6366F1",
    alignSelf: "flex-end",
    borderBottomRightRadius: 4,
  },
  messageText: {
    fontSize: 15,
    lineHeight: 20,
  },
  botMessageText: {
    color: "#111827",
  },
  userMessageText: {
    color: "#FFFFFF",
  },

  /* CHAT OPTIONS */
  optionsContainer: {
    marginTop: 8,
    marginBottom: 12,
    gap: 8,
    paddingLeft: 0,
    flexDirection: "column",
    alignItems: "flex-start",
  },
  optionButton: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1.5,
    borderColor: "#6366F1",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 16,
    alignSelf: "flex-start",
    shadowColor: "#6366F1",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  optionButtonText: {
    color: "#6366F1",
    fontSize: 14,
    fontWeight: "600",
  },
});